kana_to_romaji = {
    "あ": ["a"],
    "い": ["i", "yi"],
    "う": ["u", "wu", "whu"],
    "え": ["e"],
    "お": ["o"],
    "ぁ": ["xa"],
    "ぃ": ["xi", "xyi"],
    "ぅ": ["xu"],
    "ぇ": ["xe", "xye"],
    "ぉ": ["xo"],
    "いぇ": ["ye"],
    "うぁ": ["wha"],
    "うぃ": ["whi", "wi"],
    "うぇ": ["whe", "we"],
    "うぉ": ["who"],
    "ゔぁ": ["va"],
    "ゔぃ": ["vi", "vyi"],
    "ゔ": ["vu"],
    "ゔぇ": ["ve",  "vye"],
    "ゔぉ": ["vo"],
    "ゔゃ": ["vya"],
    "ゔゅ": ["vyu"],
    "ゔょ": ["vyo"],
    "か": ["ka"],
    "き": ["ki"],
    "く": ["ku"],
    "け": ["ke"],
    "こ": ["ko"],
    "ヵ": ["lka", "xka"],
    "ヶ": ["lke", "xke"],
    "きゃ": ["kya"],
    "きぃ": ["kyi"],
    "きゅ": ["kyu"],
    "きぇ": ["kye"],
    "きょ": ["kyo"],
    "くゃ": ["qya"],
    "くゅ": ["qyu"],
    "くょ": ["qyo"],
    "くぁ": ["qwa", "qa", "kwa"],
    "くぃ": ["qwi", "qi", "qyi"],
    "くぅ": ["qwu"],
    "くぇ": ["qwe", "qe", "qye"],
    "くぉ": ["qwo", "qo"],
    "が": ["ga"],
    "ぎ": ["gi"],
    "ぐ": ["gu"],
    "げ": ["ge"],
    "ご": ["go"],
    "ぎゃ": ["gya"],
    "ぎぃ": ["gyi"],
    "ぎゅ": ["gyu"],
    "ぎぇ": ["gye"],
    "ぎょ": ["gyo"],
    "ぐぁ": ["gwa"],
    "ぐぃ": ["gwi"],
    "ぐぅ": ["gwu"],
    "ぐぇ": ["gwe"],
    "ぐぉ": ["gwo"],
    "さ": ["sa"],
    "し": ["si", "shi"],
    "す": ["su"],
    "せ": ["se"],
    "そ": ["so"],
    "ざ": ["za"],
    "じ": ["zi", "ji"],
    "ず": ["zu"],
    "ぜ": ["ze"],
    "ぞ": ["zo"],
    "しゃ": ["sya", "sha"],
    "しぃ": ["syi"],
    "しゅ": ["syu", "shu"],
    "しぇ": ["sye", "she"],
    "しょ": ["syo", "sho"],
    "すぁ": ["swa"],
    "すぃ": ["swi"],
    "すぅ": ["swu"],
    "すぇ": ["swe"],
    "すぉ": ["swo"],
    "じゃ": ["zya", "ja", "jya"],
    "じぃ": ["zyi", "jyi"],
    "じゅ": ["zyu", "ju", "jyu"],
    "じぇ": ["zye", "je", "jye"],
    "じょ": ["zyo", "jo", "jyo"],
    "た": ["ta"],
    "ち": ["ti", "chi"],
    "つ": ["tu", "tsu"],
    "て": ["te"],
    "と": ["to"],
    "っ": ["ltu", "xtu", "ltsu"],
    "ちゃ": ["tya", "cha", "cya"],
    "ちぃ": ["tyi", "cyi"],
    "ちゅ": ["tyu", "chu", "cyu"],
    "ちぇ": ["tye", "che", "cye"],
    "ちょ": ["tyo", "cho", "cyo"],
    "つぁ": ["tsa"],
    "つぃ": ["tsi"],
    "つぇ": ["tse"],
    "つぉ": ["tso"],
    "てゃ": ["tha"],
    "てぃ": ["thi"],
    "てゅ": ["thu"],
    "てぇ": ["the"],
    "てょ": ["tho"],
    "とぁ": ["twa"],
    "とぃ": ["twi"],
    "とぅ": ["twu"],
    "とぇ": ["twe"],
    "とぉ": ["two"],
    "だ": ["da"],
    "ぢ": ["di", "ji"],
    "づ": ["du", "zu"],
    "で": ["de"],
    "ど": ["do"],
    "ぢゃ": ["dya", "ja"],
    "ぢぃ": ["dyi"],
    "ぢゅ": ["dyu", "ju"],
    "ぢぇ": ["dye"],
    "ぢょ": ["dyo", "jo"],
    "でゃ": ["dha"],
    "でぃ": ["dhi"],
    "でゅ": ["dhu"],
    "でぇ": ["dhe"],
    "でょ": ["dho"],
    "どぁ": ["dwa"],
    "どぃ": ["dwi"],
    "どぅ": ["dwu"],
    "どぇ": ["dwe"],
    "どぉ": ["dwo"],
    "な": ["na"],
    "に": ["ni"],
    "ぬ": ["nu"],
    "ね": ["ne"],
    "の": ["no"],
    "にゃ": ["nya"],
    "にぃ": ["nyi"],
    "にゅ": ["nyu"],
    "にぇ": ["nye"],
    "にょ": ["nyo"],
    "は": ["ha"],
    "ひ": ["hi"],
    "ふ": ["hu", "fu"],
    "へ": ["he"],
    "ほ": ["ho"],
    "ひゃ": ["hya"],
    "ひぃ": ["hyi"],
    "ひゅ": ["hyu"],
    "ひぇ": ["hye"],
    "ひょ": ["hyo"],
    "ふゃ": ["fya"],
    "ふゅ": ["fyu"],
    "ふょ": ["fyo"],
    "ふぁ": ["fwa", "fa"],
    "ふぃ": ["fwi", "fi", "fyi"],
    "ふぅ": ["fwu"],
    "ふぇ": ["fwe",  "fe", "fye"],
    "ふぉ": ["fwo", "fo"],
    "ば": ["ba"],
    "び": ["bi"],
    "ぶ": ["bu"],
    "べ": ["be"],
    "ぼ": ["bo"],
    "びゃ": ["bya"],
    "びぃ": ["byi"],
    "びゅ": ["byu"],
    "びぇ": ["bye"],
    "びょ": ["byo"],
    "ぱ": ["pa"],
    "ぴ": ["pi"],
    "ぷ": ["pu"],
    "ぺ": ["pe"],
    "ぽ": ["po"],
    "ぴゃ": ["pya"],
    "ぴぃ": ["pyi"],
    "ぴゅ": ["pyu"],
    "ぴぇ": ["pye"],
    "ぴょ": ["pyo"],
    "ま": ["ma"],
    "み": ["mi"],
    "む": ["mu"],
    "め": ["me"],
    "も": ["mo"],
    "みゃ": ["mya"],
    "みぃ": ["myi"],
    "みゅ": ["myu"],
    "みぇ": ["mye"],
    "みょ": ["myo"],
    "や": ["ya"],
    "ゆ": ["yu"],
    "よ": ["yo"],
    "ゃ": ["xya"],
    "ゅ": ["xyu"],
    "ょ": ["xyo"],
    "ら": ["ra", "la"],
    "り": ["ri", "li"],
    "る": ["ru", "lu"],
    "れ": ["re", "le"],
    "ろ": ["ro", "lo"],
    "りゃ": ["rya", "lya"],
    "りぃ": ["ryi", "lyi"],
    "りゅ": ["ryu", "lyu"],
    "りぇ": ["rye", "lye"],
    "りょ": ["ryo", "lyo"],
    "わ": ["wa"],
    "を": ["wo"],
    "ゎ": ["lwe", "xwa"],
    "ん": ["n", "nn", "n ", "xn"]
}

problems = [""]

def _simple_kana_to_romaji():
    output = {}

    

    # Iterate through each kana
    for kana in list(kana_to_romaji.keys()):
        if len(kana) == 1 and kana not in problems:
            output[kana] = kana_to_romaji[kana]
    
    return output

simple_kana_to_romaji = _simple_kana_to_romaji()


def _romaji_to_kana():
    """Map every romaji to kana"""
    output = {}

    # Iterate through each kana
    for kana in list(kana_to_romaji.keys()):
        romaji = kana_to_romaji[kana]

        # Seprate entry for each option
        for option in romaji:
            output[option] = romaji
    
    return output

romaji_to_kana = _romaji_to_kana()